version: '3'
services:
  main-service:
    container_name: hit-main-service
    build: "./"
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  db:
    container_name: hit-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "hit"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "hit#@!@21"
      MYSQL_ROOT_PASSWORD: "F7787D7#%ggG!D"
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - my-db:/var/lib/mysql
  redis:
    container_name: hit-redis
    image: redis
    ports:
      - "6381:6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
volumes:
  my-db:
